### ISSUE TITLE
Confirm the user pointing out some high risk vulnerability (i.e. Amount Tampering) within our add-on.

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give-PayUmoney#10]
## User Story

We have a ticket in Helpscout, where the user is claiming that they had an audit from the HDFC Bank staff and they have pointed out to some high-risk vulnerability (i.e. Amount Tampering) within our add-on.

>Dear Maruti,

>I spoke with the tech team at the HDFC Bank payment gateway integration . They told me that the reverse hash sent from the payment gateway has to be checked before logging transaction as successful .

>The information is available in detail in the integration document - page 19, 20 and 21. I am attaching the same here for your quick reference (available on GitHub as well)

## Related link
HS link: https://secure.helpscout.net/conversation/656840067/24825?folderId=1457790

## Attachment
[Integration Document Version 2.6.pdf](https://github.com/WordImpress/Give-PayUmoney/files/2360983/Integration.Document.Version.2.6.pdf)

**Comment by raftaar1191** [comment]
Get all the other details and decision of the below mention link

Slack Chat: https://givewp.slack.com/archives/C0FAGC83C/p1536321451000100
